package exceptionPractise1;

public class Calculator {
    public static int divide(int x, int y) {
//        int result = 0;
//        try {
//            if(y == 0) throw new ArithmeticException();
//            result = x / y;
//        } catch (ArithmeticException e) {
//            System.out.println("can not divide by 0");
//        }
//        return result;
//        if(y == 0) throw new ArithmeticException();
        return x / y;
    }
}
